# Generated by Django 3.2.9 on 2021-11-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='URL',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
